### ISSUE TITLE
Fix inconsistent commitActivation* methods

### ISSUE THREAD

**Issue by TomasKypta** [wultra/powerauth-mobile-sdk#114]
There are four `commitActivation*` methods, three of them return int (error code) and the fourth swallows the error code.
Method `commitActivation` ignores internal error code coming from `commitActivationWithPassword`.
The callback for the method should be extended to contain error callback method.

**Comment by hvge** [comment]
Method `commitActivation` cannot return error code, because it's asynchronous. But we definitely should handle that error code in that `onFingerprintDialogSuccess`. At this point, call to internal commit `mSession.completeActivation(keys)` usually doesn't fail, but I agree, that if you call `commitActivation` in wrong state, then It may hide the error.

**Comment by hvge** [comment]
I'm re-opening this issue. I know that I've approved the PR, but after a while, it looks like that adding that code to "success" callback is not a good idea. I've encountered this change in API, while I was migrating my "sandbox" app, and simply realized that to have "success" callback with a possible error code, is quite anti-pattern. We should add a new callback `onFingerprintDialogFailure(Throwable t)` to handle such situations properly.

Unfortunately, this has to be fixed in `develop` and also back-ported to `release/0.20.x` branch.
