### ISSUE TITLE
Add ability to add the custom HTTP headers to standard RESTful API calls

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-mobile-sdk#130]
Sometimes, the server that publishes the PA Standard RESTful API may run behind an API Management Gateway / Proxy that requires an authentication of various sorts (like an API-key, or basic HTTP, ...).

![pa-proxy](https://user-images.githubusercontent.com/516597/44149034-de3004a4-a09a-11e8-83b0-2959e46e997a.png)

Currently, there is no way to call the standard server endpoint with custom HTTP headers from the mobile SDK.

We should add a mechanism to cover all use-cases that call PA Standard RESTful API so that we allow customizing HTTP headers of the request. We should also make sure that by doing this, the SDK user does not override our HTTP headers, mainly the `X-PowerAuth-Authorization` header or `Content-Type` header.

Let's analyze the best way to approach this issue:

- adding the custom headers to every call?
- adding the authentication strategy to the HTTP client (as we do with SSL handling)?
- other? :)

**Comment by petrdvorak** [comment]
Note: I slightly prefer the approach with "authentication strategy" - this way, we can add `new BasicHttpAuthenticationStrategy(username, password)` or `new ApiKeyAuthenticationStrategy(headername, headervalue)`...

**Comment by davidvavra** [comment]
@petrdvorak @hvge Hi guys :) I'm now working for AirBank DE and we have problems related to this issue. Microsoft changed something on their API Management and now we need to send custom headers. We are thinking about some reflection-based hacks to do it, because it blocks many people from work. But it would be great to have this officially.

**Comment by hvge** [comment]
@petrdvorak yes, we can do it in this way. The only problem is that we need to implement it in two different branches of SDK, because our crypto3 branch has a complete different internal networking. But the change is quite small, so it's doable. The list of interceptors has to be a part of `PA2ClientConfiguration` and the abstract interface should be public.

So, the change will be released in upcoming SDKs version `0.20.0`, compatible with V2 servers and `1.0.0`, compatible with V3 servers.

**Comment by hvge** [comment]
Just for note. I'll wait with this until we merge #166 and #167 to appropriate branches, to prevent a mess in the branches.

**Comment by hvge** [comment]
After our internal discussion, we decided to implement this only for upcoming SDK 1.0.0 (e.g. which will work only with V3 servers). The change is ready for review.
