### ISSUE TITLE
NSURLSession leak on 0.19.3

### ISSUE THREAD

**Issue by kober32** [wultra/powerauth-mobile-sdk#183]
With current release `0.19.3` - iOS SDK is leaking  NSURLSession internals
<img width="800" alt="screenshot 2019-01-09 at 16 38 16" src="https://user-images.githubusercontent.com/5406945/50911932-349a6f00-1431-11e9-88cb-4a5e2c42417d.png">

Current develop with the new networking doesn't have  this issue, so hotfix into 0.19.x release branch should be enough.

**Comment by hvge** [comment]
This should be fixed in `release/0.20.x` instead. There's not planned `0.19.x` version for release.

**Comment by hvge** [comment]
I've just merged this into `release/0.20.x` branch, but the question is, do we need to implement similar change also in `develop`? There's a different networking code, which keeps session alive much longer.   It might leak as well, when application releases its `PowerAuthSDK` instance during the active networking operation, am I right?

**Comment by petrdvorak** [comment]
@hvge This can be easily tested with instruments, but since we keep the `UrlSession` instance as a property with the `PA2Client` instance, we can probably call this `finishTasksAndInvalidate` only when destroying the `PA2Client` instance...

Documentation: https://developer.apple.com/documentation/foundation/nsurlsession/1407428-finishtasksandinvalidate?language=objc
