### ISSUE TITLE
fingerprint authenticator lock detection

### ISSUE THREAD

**Issue by mendreuk** [wultra/powerauth-mobile-sdk#19]
When the Android user scans wrong finger 5 times in row it locks the FP authenticator for 30 secs. In our app, we would like to detect such situation and accordingly display or not a FP icon.
We don't want to show him a FP icon when the FP authenticator is locked.

**Comment by hvge** [comment]
I'm closing this issue, because this is no longer possible to implement.

We have reworked support for biometry in #226 (PR #228) and we're now using "lockout" state to simulate entering a bad credentials. That basically means that if lockout happens, then the application get the "success" status, but with the wrong biometric key. This technique effectively increases the failed attempts counter on the server and is trying to mitigate attacker who is trying to confuse the biometric sensor on the device.
