### ISSUE TITLE
Migrate artifacts to a mavenCentral

### ISSUE THREAD

**Issue by OndraBasler** [wultra/powerauth-mobile-sdk#357]
JCenter is sunseting in March 31st 2021 and will not accept new submissions after this time. JCenter will stop serving packages on February 1st 2022. Could you migrate the artifacts to other repository?

We are currently using this dependency in project `io.getlime.security.powerauth:powerauth-android-sdk:0.20.4`. Will you migrate it too?

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by petrdvorak** [comment]
Hello @OndraBasler, yes - we are aware of this issue and we are already working on mitigating the impacts. We will publish our open-source utilities on Maven Central and introduce own Artifactory for closed software bits...

**Comment by hvge** [comment]
Version `1.4.5` and `1.5.3` are now available on maven central.

**Comment by hvge** [comment]
@OndraBasler I can investigate how to re-publish older versions (like 0.20.x) but it's not on my priority list. I'm not sure whether it's possible just take package form jcenter and upload it to sonatype.org. Otherwise, the problem is that it needs time to fix the build of such old version in our current toolchains. I would suggest you to update at least to `1.4.x`
