### ISSUE TITLE
Perform full point validation during public key import

### ISSUE THREAD

**Issue by hvge** [wultra/powerauth-mobile-sdk#386]
See: https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Ar3.pdf, chapter 5.6.2.3.3.

**Comment by romanstrobl** [comment]
We should be careful when importing the point at infinity. For an EC point, this is allowed, but this value must not be allowed for a public key.

**Comment by romanstrobl** [comment]
Based on the review of OpenSSL source code in version `1.1.1`, I think that the EC point import we use in the SDK only handles checks 2) and 3) from chapter 5.6.2.3.3. The checks 1), 3) and 4) are present in function `ec_key_simple_check_key`. It may be ok to call this function after EC point import because the EC point import checks are fast, so the duplication does not matter too much.

**Comment by hvge** [comment]
The `ec_key_simple_check_key` is private function, but we can use `EC_KEY_check_key()` I think.

**Comment by romanstrobl** [comment]
Yes, that should work, in `ecp_nistp256.c` the `EC_GFp_nistp256_method` key validation method points to `ec_key_simple_check_key`. We should see that point at infinity is rejected by this call. We won't be able to verify the point order check easily, we would have to fake the P-256 curve parameters for that. If you can modify `static const struct curve_data P256` in `ec.c` inside a test, we can try to change the curve order and then the validation would fail.
