### ISSUE TITLE
Root false positive detection

### ISSUE THREAD

**Issue by navrkald** [wultra/powerauth-mobile-sdk#509]
Your client CSOB is enforcing root detection check when starting their apps. Since your SDK detects false positive root detection when is just installed app com.koushikdutta.rommanager. So in summary, my device haven't been ever rooted and this bug/false positive prevent me to use any of CSOB apps.
In summary just installed app rommanager doesn't mean device is rooted or anyhow not secure!
As well suggestion is to improve logging so user can see the reason, why his device was marked as insecure/rooted.

**Comment by petrdvorak** [comment]
The report is not related to PowerAuth.

//

The mentioned app `com.koushikdutta.rommanager` requires root to be of any use. Hence, it should trigger root detection with an appropriate level of confidence. The presence of an app indicates that the device might be rooted. Installing the app on a non-rooted device does not make much sense. The app can be safely uninstalled without losing any significant usage value.

Regarding the logging remark, we do not want to disclose details of root detection in more detail to device users since this would give actual attackers hints on how we specifically detect root. We might improve our documentation with more examples of how to work with different confidence levels during root detection.

**Comment by navrkald** [comment]
I am sorry but I don't believe answering via fuzzy logic, if device was rooted or not is good strategy, since device is either rooted or not, nothing between, I am sorry this is not quantum physics...

As well I have to disagree with obfuscating or hiding reasons why device was marked as rooted. In security relay on obfuscation is very poor strategy. I can tell you source code of the root detection can be quite easily found on internet, otherwise I would never found the reason for false positive detection on my device and for the same reason, I wouldn't tell you where I have found your source code, so other users have at least slight chance to found out false positive root detection in their case.
